global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user:9105']
        labels:
          application: 'user'
  - job_name: 'mail'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mail:9110']
        labels:
          application: 'mail'
  - job_name: 'gateway'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8762']
        labels:
          application: 'gateway'
  - job_name: 'catalogue'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalogue:9115']
        labels:
          application: 'catalogue'
  - job_name: 'auth'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth:9100']
        labels:
          application: 'auth'
  - job_name: 'reservation'
    scrape_interval: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reservation:9100']
        labels:
          application: 'reservation'
